### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by zaja** [firesale/firesale#223]
I can't get category Pagination to work, on Firesale root category click on pagination not result with anything, but if I enter in an category click on next page displaying error message:

An Error Was Encountered
The page you are trying to view does not exist and it also appears as if the 404 page has been deleted.

Please take a look:
Categories index page: http://md-filtea.hr/category/
An category example: http://md-filtea.hr/category/macke/

**Comment by jHoldroyd** [comment]
If you go to your admin section, and then go into FireSale Routes and edit your category route and make it the following:

```
Map: category/{{ slug }}{{ any }}
Route: category/([a-z0-9-]+)(:any)
Translation: firesale/front_category/index$1$2
```

I haven't tested them but they should work, I'll make sure they're added to the 1.1.1 update that'll be released early next week.

**Comment by zaja** [comment]
Thanks, but not work, how to put back pld values?

**Comment by zaja** [comment]
sorry....how to put back old values?

**Comment by jHoldroyd** [comment]
The original values are:

```
Map: category/{{ slug }}
Route: category/([a-z0-9-]+)
Translation: firesale/front_category/index$1
```

I'll take a look now and see if I can find a better fix or at least the right route config for you.

**Comment by zaja** [comment]
Thanks, I can send you admin acces if you like?

**Comment by jHoldroyd** [comment]
Ok I've just done a quick test and confirm these work:

Map: category/{{ slug }}{{ any }}
Route: category(/[a-z0-9-]+)?(/[0-9]+)?
Translation: firesale/front_category/index$1$2

**Comment by zaja** [comment]
Great man, now pagination works fine if I select an category, for example "Macke". 
But still not works on index/root categories page.

**Comment by jHoldroyd** [comment]
This should now be fixed for any new installations.

**Comment by zaja** [comment]
I see that you closed issue, maybe you missed my reply:
"Great man, now pagination works fine if I select an category, for example "Macke".
But still not works on index/root categories page."

**Comment by jHoldroyd** [comment]
Oh sorry, I didn't see the reply. I've got an idea on how to fix it, but it'll have to be included in an update rather than a simple routes fix for that issue.

**Comment by jHoldroyd** [comment]
There we go, should be taken care of now with that last commit. Just replace your categories model and front category controller and it should be all good with the routes I gave you before.

**Comment by zaja** [comment]
Great, tested and works fine. Thanks :)

**Comment by zaja** [comment]
Uh, today I can't acces any category or pagination, it's incredible, take a look (try to change page or click on any category):
http://md-filtea.hr/category

Category Route setting:
http://screencast.com/t/ktfRihv3a
