### ISSUE TITLE
Image upload [bug?]

### ISSUE THREAD

**Issue by FornetMK** [firesale/firesale#248]
FireSale version 1.1, on the latest PyroCMS Pro. Browser: Google Chrome.
1. I create product, have it done, I want to add image.
2. I hit edit, have image tab on, I drag image there, and here comes the problem:
   
   there is obviously try of upload - but it does stop in half of the way, and I get the error statement.

![image-err](https://f.cloud.github.com/assets/2280617/14629/70b63684-4658-11e2-88af-efa8b017c669.png)

Checking the files option gives info that the module has created image folder, but did not save image there. Uploading images to that folder (via Files module) - makes everything ok, image is shown on the product page.

If the idea was, that each product - while created - has "future-images" folder done, maybe the bug is just there. That the folder is not created, while product is saved first time.

**Comment by jHoldroyd** [comment]
Generally what causes this issue is incorrect write permissions on the uploads directory. It should have been fixed for 1.1 but if you can update to either 1.1/develop or 1.2/develop and see if it keeps happening if the permissions are correct.

**Comment by FornetMK** [comment]
It is not the fault of directory permissions. I have manually changed to 777 for the test (had 755) - and the problem still happens.

By the way, it cannot be that, because if it would be file permissions - no files could not be uploaded by any means. And they can be - by standard file module. 

-edit-

I have double checked. 

I have 777 on uploads, then 777 on "default" (site name in site manager), then 777 on "files"  - still does not work. I have also changed owner of the folders (I do not know config of my server well and why some things are like that - probably security), default and files were owned by apache, now they are owned by "hosting user". still no effect. and it does not work.

**Comment by jHoldroyd** [comment]
I only mention it because that's the only time we've seen this issue since changing the way we create a folder; which is in the 1.1/master branch. I'll do some more testing and see if I can replicate it but I think it's all working on this end at the moment.

**Comment by jHoldroyd** [comment]
Ok I've been trying to replicate this for a while and the only issue I've found is that a successful upload doesn't count as that to the JS when something is output before the JSON string so it can't parse it. The folder issue is confusing to say the least as we use all of the built in methods from files with a few small tweaks that don't really matter to the script...I have no idea what to do about this.

**Comment by jHoldroyd** [comment]
Ok after more attempts to replicate this on a range of servers, still no joy. We're closing this until we get more confirmations that it's happening on newer 1.2/develop builds.
