### ISSUE TITLE
500 Server Error when using Order Filters

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#415]
In the Orders admin area I always receive a 500 Server error when trying to use the filters.

Looks like the ajax request possibly isn't picking up the filters used and is trying to return a 404 page.

Ajax request:
/admin/firesale/orders/ajax_filter/undefined

and the server error is:
Unable to load the requested file: 404.html

**Comment by iknowfoobar** [comment]
Was this ever created? It looks like this functionality was never completed or is missing some files? There doesn't appear to be an action to respond to the filters and return the ajax response.

**Comment by AJSturrock** [comment]
Looks like the path wasn't updated when we changed the directory structure, should be fixed in 8631f02108411c701eb48cbc7c633429f7c0223b

Can you let me know if this fixes the issue and I'll close, thanks.

**Comment by iknowfoobar** [comment]
Hi Adam, I still get a 404 error using the url /admin/firesale/ajax/ajax_filter
Well I actually get a 500 but that is because it can't find the 404.html template.

**Comment by AJSturrock** [comment]
Hi Giles, it should be /admin/firesale/ajax/order_filter

**Comment by iknowfoobar** [comment]
Excellent sorry misread the commit, working thanks!

**Comment by iknowfoobar** [comment]
Hi Adam, are you able to get all the latest fixes pulled into firesale pro? Cheers
