### ISSUE TITLE
Clean up a mistaken commit

### ISSUE THREAD

**Issue by jHoldroyd** [firesale/firesale#54]
Earlier I accidentally committed a number of changes for a work-in-progress project that breaks the current cart, users are advised to not update their install until this issue has been closed. I'm going to assign it to Chris since it's his area and I want to make sure it's not going to compromise the current cart and buying steps.

Apologies for anyone affected and I would rollback the commit, but there were also a number of intended fixes included in it that would also brake if we did that.

**Comment by chrisnharvey** [comment]
Didn't realize that this was an issue. I fixed this earlier. Closing.

**Comment by from2day** [comment]
How should add to cart work? 
It still doesn't add product to the cart.
